---
- name: Install/Uninstall s/w application
  hosts: all
  become: true
  vars: 
   - a: tomcat9
   - b: present
   - c: no
  tasks: 
   - name: Install?uninstall
     apt:
      name: "{{a}}"
      state: "{{b}}"
      update_cache: "{{c}}"
...
