---
- name: Create users and create file/dir in the users home dir
  hosts: all
  become: true
  tasks:
   - name: create users
     user:
      name: "{{a}}"
      password: "{{b}}"
      home: "{{c}}"
   - name: Create files/dirs in the users home dir
     file:
      name: "{{d}}"
      state: "{{e}}"
...
