---
- name: Configuring apache2
  hosts: all
  tasks:
   - name: Install apache2
     apt:
      name: apache2
      state: present
      update_cache: yes
   - name: Edit the index.html file
     copy: 
      content: "Sunny Boy"
      dest: /var/www/html/index.html
   - name: Restart apache2
     service: 
      name: apache2
      state: restarted
   - name: Check url response of apache2 on all the servers
     uri:
      url: "{{item}}"
      status_code: 200
     with_items: 
      - http://172.31.11.239
      - http://172.31.0.122
      - http://172.31.41.47
      - http://172.31.46.28
...
