---
- name: Implementing docker compose using ansible
  hosts: all
  tasks:
   - name: Create a mysql container
     docker_container:
      name: mydb
      image: mysql
      env:
       MYQSL_ROOT_PASSWORD: sunny
   
   - name: create a wordpress container
     docker_container:
      name: mywordpress
      image: wordpress
      ports:
       - 8989:80
      links:
       - mydb:mysql
...



